Add isUnicode parameter to StringLiteralQueryType function
FirebirdSQL/NETProvider pull request #1192
Opened 2024-09-24 13:23 UTC by gilsonjoanelo

included the isUnicode parameter in the StringLiteralQueryType method so that it can be turned off if desired. tests performed on Firebird 4 and Firebird 5

2024-09-25 17:44 UTC, cincuranet requested changes

2024-09-25 17:44 UTC, cincuranet commented on src/FirebirdSql.EntityFrameworkCore.Firebird/Storage/Internal/FbSqlGenerationHelper.cs
> +		if(isUnicode)
Use ternary operator.

2024-09-25 23:12 UTC, gilsonjoanelo commented
code changed, do I send a new PR?

2024-09-26 06:58 UTC, cincuranet requested changes

2024-09-26 06:58 UTC, cincuranet commented on src/FirebirdSql.EntityFrameworkCore.Firebird/Storage/Internal/FbSqlGenerationHelper.cs
> +		var charset = isUnicode ? " CHARACTER SET UTF8" : "";
Use `string.Empty` instead of `""`.

2024-09-26 06:58 UTC, cincuranet commented
No need to send new PR.

2024-09-26 11:36 UTC, gilsonjoanelo commented
changed to string.empty

2024-09-26 11:44 UTC, cincuranet approved these changes

2024-09-26 11:44 UTC, merged