Scaffolding setup now supports Firebird 2.5
FirebirdSQL/NETProvider pull request #976
Opened 2021-08-01 19:23 UTC by SJFriedl

This adds scaffolding support for versions of Firebird < 3.0 (tested on 2.5) by eliding the `rdb$IDENTITY_TYPE` column if the version is too old - it uses the same logic as found in the `FbColumns.cs` support elsewhere.

This works well enough to create the raft of files representing each table, but it hasn't be tested for anything beyond that as Jiri has said other updates need to be done. So this is only an incremental step.

2021-08-04 06:28 UTC, cincuranet requested changes

2021-08-04 06:28 UTC, cincuranet commented on Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Scaffolding/Internal/FbDatabaseModelFactory.cs
> +			if (connection.State == ConnectionState.Open)
At this point connection is known to be open.

2021-08-04 06:28 UTC, cincuranet commented on Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Scaffolding/Internal/FbDatabaseModelFactory.cs
> +				var serverVersion = FbServerProperties.ParseServerVersion(connection.ServerVersion);
I would put this into `DatabaseModel Create(DbConnection connection, DatabaseModelFactoryOptions options)` method and create a property for it.

2021-08-04 06:28 UTC, cincuranet commented on Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Scaffolding/Internal/FbDatabaseModelFactory.cs
> +				if (serverVersion.Major >= 3)
Store `MajorVersionNumber` directly, to make it easier for future.

2021-08-19 06:45 UTC, cincuranet commented
@SJFriedl Are you going to finish this PR?

2021-11-10 12:31 UTC, cincuranet commented
Done via faedc6e7.

2021-11-10 12:31 UTC, closed without merging

2023-11-14 12:58 UTC, lvalgimigli commented
I have this error when scaffolding a 2.5 Firebird database:

2023-11-14 12:59 UTC, lvalgimigli commented
I have this error when scaffolding a 2.5 Firebird database: Could not find type mapping for column 'XXXXX' with data type 'NUMERIC(4,2)'. Skipping column.

2023-11-15 09:24 UTC, mrotteveel commented
Please report bugs by creating new issues, or if you're asking for help, ask on [firebird-net-provider](https://groups.google.com/g/firebird-net-provider)

2023-11-15 13:53 UTC, cincuranet commented
@mrotteveel He did: https://github.com/FirebirdSQL/NETProvider/issues/1142.